name: Unit Test
on:
  push:
  # schedule:
    # - cron: '0 23 * * *'
jobs:
  Run:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        persist-credentials: false
    - name: Use Go 1.18
      uses: cedrickring/golang-action/go1.18@1.6.0
    - name: Run Test
      run: |
        go test -bench=. -benchmem -race --cover -v ./...
