name: Unit Test
on:
  push:
  # schedule:
    # - cron: '0 23 * * *'
jobs:
  Run:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        persist-credentials: false
    - name: Use Go 1.18
      uses: actions/setup-go@v3
      with:
        go-version: '1.19.1'
    - name: Run Test
      run: |
        go test -bench=. -benchmem -race --cover -v ./...
